[build]
builder = "DOCKERFILE"
nixpacksPlan = {"providers":["...","go"]}
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10